const CHANGE_VOLUME = "CHANGE_VOLUME"
const POWER_SWITCH = "POWER_SWITCH"
const BANK_SWITCH = "BANK_SWITCH"
const BUTTON_PRESS = "BUTTON_PRESS"

export {
  CHANGE_VOLUME,
  POWER_SWITCH,
  BANK_SWITCH,
  BUTTON_PRESS
}